### ISSUE TITLE
how do you install vencord on this and is this better then armcord for performance

### ISSUE THREAD

**Issue by Pickymarker** [SpikeHD/Dorion#11]
how do you install vencord on this and is this better then armcord for performance

**Comment by SpikeHD** [comment]
I don't use ArmCord, so I have no idea. I wouldn't even really know how to measure performance between them.

This is changing soon, but to install Vencord, download their [`browser.js` script](https://github.com/Vendicated/Vencord/releases/tag/devbuild). Then:
* Create a folder in your plugins folder named "vencord" (or whatever you want, this doesn't really matter). Find your plugins folder by clicking this folder icon.
![image](https://user-images.githubusercontent.com/25207995/204168728-7d9419a7-828b-44ab-8764-d5ece4229dc0.png)
* Place the `browser.js` script your downloaded into the folder you just made, and rename it to `index` instead of `browser`.
* Reopen Discord settings, and it should appear. Ensure it is both enabled AND set to "Preload"
![image](https://user-images.githubusercontent.com/25207995/204168823-61c2ff00-d03b-4b64-9c28-64edec165c5e.png)
* Click "Save and restart", or just press Ctrl+R to reload the client.

**Comment by SpikeHD** [comment]
This has changed in `v0.4.3`. Just place `browser.js` in your plugins folder and rename it to `vencord.js` or whatever

**Comment by bluueray** [comment]
> Just place `browser.js` in your plugins folder
i can't open my settings after that

**Comment by SpikeHD** [comment]
This was happening to me to, I believe it's a problem with Vencord. I'll take a look sometime but if that is the case, not much I can do about it.
