### ISSUE TITLE
[Feature Request] OG Title Bar

### ISSUE THREAD

**Issue by FortNbreak** [SpikeHD/Dorion#113]
I wish Dorion could feel like normal discord. It would make it better with themes that utilize the title bar and make custom buttons on the title bar and stuff.

One solution that is bad but might work is decompiling Discord's app.asar and look for a file that adds the title bar and add it to Dorion as a custom title bar or something.

An alternative is trying to add theme support for the title bar that Dorion uses

It would be cool :)

**Comment by SpikeHD** [comment]
If you know of a theme that utilizes the title bar in the ways you mention feel free to comment it here. The problem with replicating the title bar one-to-one is that the class names may shuffle and change when Discord updates, meaning hard-coding them would require changing them whenever that happens.

I don't really feel like checking the regular Discord app every so often just to see if I need to replace class names, so I am willing to find a compromise depending on what sort of selectors themes use to get it. If most themes just *also* hardcode it (eg. they use `.titleBar-8jk7y {}` or whatever instead of something more versatile like `div[class^="titleBar"]) {}`, then I am not going to bother.

**Comment by snixf** [comment]
![image](https://github.com/SpikeHD/Dorion/assets/84739184/4c535241-1765-4457-9125-8ca5b3124183)
i accidentally deleted just one file while looking through dorion files to see is there any config and it looks like this now and im loving it

**Comment by SpikeHD** [comment]
"Use Native Titlebar" in Dorion Settings 👍

**Comment by piotr25691** [comment]
> I wish Dorion could feel like normal discord. It would make it better with themes that utilize the title bar and make custom buttons on the title bar and stuff.
> 
> One solution that is bad but might work is decompiling Discord's app.asar and look for a file that adds the title bar and add it to Dorion as a custom title bar or something.
> 
> An alternative is trying to add theme support for the title bar that Dorion uses
> 
> It would be cool :)

Also, the Dorion title bar can already be themed. I did it and it looks nicer

**Comment by SpikeHD** [comment]
Closing since it's pretty easy to theme the Dorion titlebar with custom CSS now, and I don't intend on keeping up with the class name changes of the official titlebar just to replicate it.
