### ISSUE TITLE
[Bug] Vencord's Quick CSS doesn't work

### ISSUE THREAD

**Issue by Anime-Forevere** [SpikeHD/Dorion#130]
**Describe the bug**
When I try to open Quick CSS in Vencord's settings using Dorion, I get "You'll need a new app to open this about link"

**To Reproduce**
1. Go to Vencord settings
2. Click "Open QuickCSS file"

**Expected behavior**
Quick CSS editor should open

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/56559528/e08c1f4e-0d3d-4b91-9062-f6106a336f49)

**System Info (please complete the following information):**
 - OS: Windows 10 LTSC (21H2 19044)
 - Version: v1.4.0

**Additional context**
I think that it tries to open a link with `about` protocol.
Also, if you import Vencord settings, Quick CSS gets applied and is usable.

**Comment by SpikeHD** [comment]
I was debating moving QuickCSS to a settings tab in my fork because I don't *think* Tauri properly supports that type of separate window on all platforms, but now that I plan to [move to Shelter](https://github.com/SpikeHD/Dorion/tree/shelter-move), I'll just make an inline-CSS editor plugin for that instead. Don't expect the QuickCSS editor *specifically* to ever work, but you can expect *a* CSS editor sometime soonish.

**Comment by RavenCutie21** [comment]
snazzy shelter has quick css in it, its a plugin from yellowsink, but the tab specifically doesnt seem to work under dorion currently.

**Comment by SpikeHD** [comment]
Ahh yes right I knew I saw it already somewhere, I might just see what's up with it, fix it, and include it by default

**Comment by SpikeHD** [comment]
I have decided to instead make my own inline CSS editor for Shelter since Monaco is being a pain to get working (and it's huge!). It's located in [my shelter-plugins repo](https://github.com/SpikeHD/shelter-plugins) and you can add it right now if you'd like, or wait til next release, up to you!
