### ISSUE TITLE
[Bug] Notifications showing twice and are "too slow"

### ISSUE THREAD

**Issue by Daki0082** [SpikeHD/Dorion#159]
**Describe the bug**
"Too slow": Whenever someone sends me many messages in a few seconds (on normal Discord client), the previous windows notification goes away quickly to make room for the new one. This doesn't happen in Dorion. I don't know if it's a bug or not, but it's something I noticed.

Notification showing twice: Whenever I get a message on Dorion the windows notification appears for a few seconds, but after it disappears it shows again, as if the person sent the same message twice.

**System Info**
 - OS: Windows 11
 - Version: v2.2.1

**Comment by SpikeHD** [comment]
For the first problem, I don't think I have any control over the notifications lifetime like that since I use inbuilt Tauri functionality for it.

For the second problem, it should be fixed in https://github.com/SpikeHD/shelter-plugins/commit/64f919596875199c8f48bccc25f44ffbc297c530 (shelter plugins auto-update, nothing needs to be done on your end)
