### ISSUE TITLE
What does this project do differently than the usual Discord Client?

### ISSUE THREAD

**Issue by pegvin** [SpikeHD/Dorion#168]
I was in the Hopes that this project might be using Native UI Libraries or A Custom One.

Since Tauri Apps Might Be Small in Size But Tauri is mostly like Electron at the end of the day.

Electron ships with the 'Browser', While Tauri uses the one's that come with the OS or need to be installed.

**Comment by SpikeHD** [comment]
> Electron ships with the 'Browser', While Tauri uses the one's that come with the OS or need to be installed.

Seems you already know the answer to your question! 

Dorion aims to create small binary sizes by using the Web version of Discord with Tauri, and then recreating a lot of the desktop specific features from scratch (and, of course, making them optional to help with performance for people that don’t want them). RPC, Streamer Mode detection, etc. are all custom reimplementations written in Rust, using the Shelter client mod to facilitate communication between backend and frontend.

On top of that, like most other clients, it supports plugins and themes, with a couple caveats but also an improvement (that being theme caching, which will save all externally-fetched CSS imports, images, etc. locally to the disk. Also optional of course)

Dorion doesn’t do anything particularly groundbreaking, but the hope is that native webview + using the web version yields better performance and load times. While I don’t have, like, solid reproducible benchmarks to back anything up, I’ve had many people in the Discord say they prefer it due to it succeeding in those two aspects.
