### ISSUE TITLE
[Feature Request] Detect connection status when starting up

### ISSUE THREAD

**Issue by takase1121** [SpikeHD/Dorion#169]
**Is your feature request related to a problem? Please describe.**
I am working on a metered connection, so I don't always have Internet access when Dorion starts. Dorion shows the edge Internet error page, which is quite ugly.

**Describe the solution you'd like**
Dorion should inject its own JS earlier in startup, checking Internet connectivity and shows a "retrying connection" page instead of showing Edge's own Internet issue page.

**Describe alternatives you've considered**
1. Crashing Dorion (bad idea)
2. Keep it as-is (not bad, but could be better)

**Additional context**
![image](https://github.com/SpikeHD/Dorion/assets/20792268/1a957091-49d9-4fde-99ff-f9d7f065fb3f)

**Comment by takase1121** [comment]
To replicate this issue, I deleted `%APPDATA%/Roaming/dorion` folder before restarting.

**Comment by SpikeHD** [comment]
If memory serves me right, that page should only appear if Dorion had never loaded Discord before, since (I think) future openings of Dorion will load the cached stuff and show the Discord loading spinner infinitely as it should. Either way, don't totally think I have control over this page anyways, so I'll be closing this.
