### ISSUE TITLE
[Bug] Dorion is detected by antivirus software

### ISSUE THREAD

**Issue by KonerDev** [SpikeHD/Dorion#182]
**Describe the bug**
The Dorion Client is classified as a virus  by two antivirus programs, including Google. Can you fix this somehow? This scares me because I don't know if I should install Dorion now
https://www.virustotal.com/gui/file/baec321ddc933ab56ba9336bb6891a175aed4ff66152658d02f8e50b6a210cea/detection

**To Reproduce**
Download dorion portable zip in Google Chrome or upload portable zip to virustotal.com

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/105141148/2a732d94-e7c8-443f-8a3c-e61e4c1c8bc2)

**System Info (please complete the following information):**
 - OS: Windows 11

**Comment by SpikeHD** [comment]
This is a false positive. Obviously don't just take this from me, but *usually* when a program only has one or two detections out of 60+, its likely not a problem. I also have had people using Windows Defender get alerts, but that is just because I don't sign the executable with Microsoft and it's usually by a machine-learning based detection (almost always `Bearfoos.A!ml`, the "ml" meaning "machine learning" from what I know).

My guess for the Ikarus detection is that it detects Discord URLs within the binary and thinks is a password stealing program. Since the Google one doesn't really give details, I have no idea what that one could be triggered by.

If you do not trust the release binaries, I welcome you to take a look at the code yourself to ensure there is nothing shady going on. Once/if you are confident that its okay, you can also download a release binary from [GitHub Actions](https://github.com/SpikeHD/Dorion/actions/workflows/build.yml) in case you feel like I am putting something in the releases. I recommend putting `branch:v[version number]` in the search bar to find the exact same build as what would be in the releases (for example, `branch:v3.1.1` for this current version), so you're not behind/ahead. You can also [review the build.yml](https://github.com/SpikeHD/Dorion/blob/main/.github/workflows/build.yml) in order to ensure the automated build doesn't have anything funky going on either. If you are willing, you can also just build it yourself locally!

You can also check in with other Dorion users in the Discord if you are still unsure or have any questions!
