### ISSUE TITLE
Add setting to open links in default browser

### ISSUE THREAD

**Issue by Liz-chan** [SpikeHD/Dorion#2]
Currently, any link or image you try to open in Dorion opens in the Edge Webview, but I'd much prefer for it to open in my default browser like how the regular Discord client does it. I'm not seeing any setting to enable that at the moment, so I think it'd be a nice improvement to add.

**Comment by SpikeHD** [comment]
[Gotta be Webview unfortunately](https://github.com/tauri-apps/tauri/issues/3655#issuecomment-1065211583). I considered this while first creating the project but for now it is not a possibility.

**Comment by Liz-chan** [comment]
That's unfortunate, I really like the app and it's nice and fast but if links always have to open in the Webview I don't think I could use it for long and might just go back to the stable client. Thank you for looking into it though!

**Comment by SpikeHD** [comment]
Oops sorry randomly came back to this and re-read, this is totally possible lmfao excuse my sleep deprivation

**Comment by Liz-chan** [comment]
Hey thanks for the update! I can confirm that links on 0.4.0 open in my browser now 😄

**Comment by SpikeHD** [comment]
Huh! So they do! I didn't even notice that the recent update fixed it, but I'm, glad to hear it!

**Comment by Liz-chan** [comment]
Actually, it seems that when you click on a link with the left mouse button it opens in the default browser, but when you middle click an image (to open the full size image) or a link, it opens in the Webview instead. Should be easily fixable I'm guessing since the main part of it is already complete.

**Comment by LothaireCliquennois** [comment]
Still having the possibility to open them in Webview is a good thing.
It's more of a "native Windows" move, because if you're using an SAC version of Windows 10 (e.g Home, Pro, Enterprise, Education and so on) Edge Webview is most likely already in RAM.
For LTSC, Win7, 8.1, and Server users, yes it may be less convenient as Edge isn't always here by default, and even when installed, the integration isn't as tight with the system.

**Comment by SpikeHD** [comment]
While I have no plans right now to add functionality to choose between the default browser and the Webview (partially because MacOS doesn't support separate WebView windows in that way, from my experience), the majority of links should now properly open normally as of https://github.com/SpikeHD/Vencordorion/commit/08d2446d6f26d7aee9b9b3e11c80ad2934be74e2
