### ISSUE TITLE
[Bug] Activities don't load (possible authorization issue)

### ISSUE THREAD

**Issue by Banaanae** [SpikeHD/Dorion#221]
**Describe the bug**
Putt Party doesn't load, just shows white screen

**To Reproduce**
1. Join VC
2. Start and activity
3. Press Putt Party
4. Observe white screen

**Expected behavior**
Putt party loads

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/83927639/c17c3366-c837-43d0-9d69-7ae614094af4)
![image](https://github.com/SpikeHD/Dorion/assets/83927639/3749920d-e721-452d-9250-6523ba11ea56)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v4.1.3
 - Any other relevant info: 

**Additional context**
Other activities make it to loading screen but not into game, but no errors in console.
May be bigger than putt party

**Comment by Banaanae** [comment]
Looks like there's issues with authorization,
Every time I restart an activity it asks for authorization again
It might be the case that it's also failing to check if it's already authorized? (speculation) I used many activities (including ones I'vw played before) and none loaded

**Comment by SpikeHD** [comment]
I don't think this is an authorization issue. After like 5 seconds of mindless digging, I can see it attempting to call `window.chrome.webview.postMessage()` (perhaps because something is making it think it's running on the Desktop client? Dunno), which doesn't exist.

Since it runs via iframes, it might require some sort of monkeypatch in `preinject.ts` or `injection.ts` to fake the existence of this function or something, idk

**Comment by SpikeHD** [comment]
Fixed as of 8c9b2f24c35354435ebe8ae4d1f7661c36d4085a, will be available in the next release 👍
