### ISSUE TITLE
[Bug] fix transparent, and blur themes

### ISSUE THREAD

**Issue by Scrapper1824** [SpikeHD/Dorion#223]
**Describe the bug**
when using transparent, or blur themes the theme turns everything white

**To Reproduce**
use a theme like ClearVision // https://betterdiscord.app/theme/ClearVision

**Expected behavior**
the theme will work with no issues like when I use vencord on my browser

**Screenshots**
![Screenshot 2024-04-16 224007](https://github.com/SpikeHD/Dorion/assets/72410525/07b4c3ab-cf97-40b0-981a-48b1edc2b053)
![Screenshot 2024-04-16 224011](https://github.com/SpikeHD/Dorion/assets/72410525/bb49d81e-1c41-453f-a41b-bc7f35abc2f5)

**and this is what it looks like on vencord**
![Screenshot 2024-04-16 224203](https://github.com/SpikeHD/Dorion/assets/72410525/97f27e9c-5e35-40c8-8c4c-9edadf0a6d1e)
![Screenshot 2024-04-16 224212](https://github.com/SpikeHD/Dorion/assets/72410525/574c6b46-e300-4d89-bc70-71ceb1548967)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v4.1.3

**Comment by SpikeHD** [comment]
Issues with background-image-based themes are due to [known, unfixable*](https://github.com/SpikeHD/Dorion?tab=readme-ov-file#known-issues) issues that have a couple workarounds if you search around these issues or [the Discord](https://discord.gg/agQ9mRdHMZ).

If you'd like to use a theme that takes advantage of transparent windows. enable a blur type near the bottom of "Performance & Extras".

**Comment by Scrapper1824** [comment]
blur doesn't work ether with or without a theme

**Comment by SpikeHD** [comment]
Unsure what you mean by this, can you give some extra detail? What "blur" are you referring to?
