### ISSUE TITLE
Failed makepkg[Bug]

### ISSUE THREAD

**Issue by novadecay** [SpikeHD/Dorion#236]
**Describe the bug**
extra comma in PKGBUILD depends array causes build failure

**To Reproduce**
1. git clone the current main branch or download the latest zip release (4.3.0)
2. run "makepkg"

**Expected behavior**
successful package build.

**System Info (please complete the following information):**
 - OS: 6.9.1-arch1-1
 - Version: 4.3.0

**Comment by SpikeHD** [comment]
The PKGBUILD in the repo just exists for reference atm. I don't maintain Dorion on the AUR, someone else does, so I just lazily Ctrl+F replace the old version number with the new one when I make a version bump commit, so the hash has never changed.

The intention, iirc, is that one day I or the maintainer would make it git based instead of based on a release download, but that hasn't happened yet and I can't say I really intend to anytime soon. The `depends` typo is fixed now though 👍
