### ISSUE TITLE
[Bug] AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer

### ISSUE THREAD

**Issue by SuperMeepBoy** [SpikeHD/Dorion#237]
**Describe the bug**
The app is a grey screen, nothing loads. When I run it from my terminal I get `AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer`

**To Reproduce**
Steps to reproduce the behavior: start the app

**Expected behavior**
The app starts with components showing to log in, start chatting, etc.

**System Info (please complete the following information):**
 - OS: Garuda (Arch)
 - Version: BirdOfPrey Soaring and Kernel is 6.9.3-zen1-1-zen (64-bit)
 - Any other relevant info:  I use X11 and I have Nvidia graphic card

**Comment by SpikeHD** [comment]
Looks like there is a [related upstream issue](https://github.com/tauri-apps/tauri/issues/9304), try doing this fix mentioned in [this comment](https://github.com/tauri-apps/tauri/issues/9304#issuecomment-2028409103)

**Comment by SuperMeepBoy** [comment]
Adding it in /etc/environment did not fix it. But running the command with `WEBKIT_DISABLE_DMABUF_RENDERER=1` as a prefix did work tho.

I guess I'll have to check an alternative for /etc/environment.

**Comment by SpikeHD** [comment]
Glad that works! I'll see if I can find an easy way to detect GPU vendor and set the env var accordingly

**Comment by SpikeHD** [comment]
This should hopefully be fixed in f8ef9af, feel free to try an Actions build or just wait til the next release. If it still doesn't work lemme know 👍

**Comment by SuperMeepBoy** [comment]
Adding a comment for people like me who wonder why it does not work after adding `WEBKIT_DISABLE_DMABUF_RENDERER=1` in `/etc/environment`, I had to reboot my computer ! :)

**Comment by goyalyashpal** [comment]
> running the command with `WEBKIT_DISABLE_DMABUF_RENDERER=1` as a prefix did work tho.
> \- @ SuperMeepBoy at https://github.com/SpikeHD/Dorion/issues/237#issuecomment-2155586392

thanks a lot for this. 

how can this be set up in nixos?

**Comment by SpikeHD** [comment]
@goyalyashpal  Assuming you are on an NVIDIA card (which iirc is where the problem lies), Dorion should properly automatically detect it and set the environment variable.

If you're still having the problem (as in, Dorion isn't detecting your GPU for some reason so you're getting the same issue), you can [consult the NixOS documentation](https://nixos.wiki/wiki/Environment_variables) on env variables (that's all I can point you to though, I don't use Nix :P)

**Comment by goyalyashpal** [comment]
> you can [consult the NixOS documentation](https://nixos.wiki/wiki/Environment_variables) on env variables

thanks a lot 😇😇




> Assuming you are on an NVIDIA card (which iirc is where the problem lies)

wowww, so root of 90-99% of the problems i am facing in linux is due to nvidia 😂😂

its kinda amazing to me 😄

> Dorion should properly automatically detect it and set the environment variable

i ran it via `nix-shell -p whatsapp-for-linux` which runs the apps in an isolated environment. i think maybe doing proper install will allow the app to set those.

i will try that a bit later. would u need an update on this?

**Comment by SpikeHD** [comment]
> would u need an update on this?

It wouldn't hurt to leave one here for other NixOS users. I don't use Nix nor do I maintain the Dorion Nix package, so it won't be helpful to *me* specifically, but I'm sure it would help other users that may come across this!

**Comment by goyalyashpal** [comment]
> Dorion should properly automatically detect it and set the environment variable.
> \- @ SpikeHD at https://github.com/SpikeHD/Dorion/issues/237#issuecomment-2265965363

i think that would have to be specified in the `.nix` file for the wfl package; otherwise the conventional methods of env-var setting likely don't work in nixos as far as i understand it.


[wfl]: https://search.nixos.org/packages?show=whatsapp-for-linux&query=whatsapp "whatsapp-for-linux on nix-pkgs"
[hmsv]: https://home-manager-options.extranix.com/?query=sessionVariables "home.sessionVariables"
[envvar]: https://search.nixos.org/options?show=environment.variables



so, 
* on adding the [`whatsapp-for-linux`][wfl] to `home.packages` attibute, i still required to set the env-var. otherwise it showed same error as above.
* and setting that via [`home.sessionVariables`][hmsv] didn't work
* so, i had to do that too via [`environment.variables`][envvar]


```nix
  # Did NOT work
  # home.sessionVariables = {
  #   WEBKIT_DISABLE_DMABUF_RENDERER = "1";  
  # };

```


```nix
  environment.variables = {
    WEBKIT_DISABLE_DMABUF_RENDERER = "1";
  };
```

**Comment by goyalyashpal** [comment]
i don't know why, but this command `whatsapp-for-linux` requires running 2 times to launch the whatsapp, which is not possible on CLI since the first run is blocking as well. 

so, while "test-installing" WFL (i.e. the start menu doesn't includes it yet), i used the cinnamon DE's "Run dialog" i.e. `alt-F2` to do the double run to launch.

**Comment by averyterrel** [comment]
Um.. how is this related to Dorion? whatsapp-for-linux is an entirely different program made by different people

**Comment by goyalyashpal** [comment]
ohw, sorry, i thought it was same.  sorry, it was a mistake then.
