### ISSUE TITLE
[Bug] Dorion removed by windows security 

### ISSUE THREAD

**Issue by khewweifeng** [SpikeHD/Dorion#269]
**Describe the bug**
Dorion removed by windows security 

**To Reproduce**
-

**System Info (please complete the following information):**
 - OS: Edition	Windows 11 Home Single Language
Version	23H2
OS build	22631.4391
Experience	Windows Feature Experience Pack 1000.22700.1047.0

 - Extra Client Mods/Plugins: None
    - Under most circumstances, you should always try disabling client mods/plugins before reporting a bug! This way, if it is the fault of a plugin, you can make note of that.
 - Any other relevant info: 

**Additional context/Screenshots**

![Screenshot 2024-10-27 160533](https://github.com/user-attachments/assets/56b3eb2a-d00c-4e5b-b55f-1b4693e52b11)
![Screenshot 2024-10-27 160546](https://github.com/user-attachments/assets/0cc90a9e-dbff-48c7-8c76-fec3ea4984fe)

**Comment by SpikeHD** [comment]
This is a semi-common problem, at least partially caused by the fact that I do not codesign the binaries. Dorion is also only EVER detected by AI/ML based detectors, which is annoying. You can see #182, #196, #226, or #227 for more context.

I encourage you to put Dorion through [Virustotal](https://www.virustotal.com) if you don't trust me! Or, if you have the know-how, you can review the code yourself and build Dorion using the [build instructions](https://github.com/SpikeHD/Dorion?tab=readme-ov-file#building)
