### ISSUE TITLE
[Feature Request] Use Discord's titlebar

### ISSUE THREAD

**Issue by luximus-hunter** [SpikeHD/Dorion#274]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Show Discords own titlebar.

**Additional context**
I've looked around for a bit, but couldn't find any flags to enable. Easiest way will just to crate a replica of the discord titlebar

**Comment by SpikeHD** [comment]
This has been suggested before (#222) and the reason I don't want to do it is because Discord's CSS class names change all the time, which means if I were to say, recreate it using the same class names, I would have to push Dorion updates every week just to keep up.

I too couldn't find anywhere to hook and enable the titlebar (though I only looked briefly), and honestly I don't think it's worth it, even [LegCord](https://github.com/Legcord/Legcord/blob/554537cda42c4f172aaf893a26f007f1d5094d9e/src/discord/preload/titlebar.mts#L7) just runs their own. The existing titlebar also uses Discord's CSS color variables so it should match most themes to an extent anyways.
