### ISSUE TITLE
U just can`t open the Dorion Clinet

### ISSUE THREAD

**Issue by Amir3istaken** [SpikeHD/Dorion#29]

**Comment by SpikeHD** [comment]
Have you tried:
* Installing via MSI instead of the  `.zip` file?
* Using the `.zip` file instead of the MSI?
* (If using the `.zip` file) making sure all files were extracted properly (`html`, `injection`, etc.)
* [Reinstalling WebView2?](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)

(Looks like it's time for issue templates lol)

**Comment by SpikeHD** [comment]
Closing as there has been no response
