### ISSUE TITLE
[BUG] Vencord Themes not working

### ISSUE THREAD

**Issue by Mason-17** [SpikeHD/Dorion#52]
**Describe the bug**
Vencord based theming doesn't work at all.

**To Reproduce**
1. try to import theme regularly via link
2. app reports the file can't be fetched
3. try manually adding .css file
4. app hangs on startup trying to import a .svg file, and have to press space to bypass

**Expected behavior**
Theme should import regularly.

**Screenshots**
If applicable, add screenshots to help explain your problem
![Screenshot 2023-07-31 161233](https://github.com/SpikeHD/Dorion/assets/122631948/0aa0556a-f8bf-4bd7-8413-bcca33571c9d)

**System Info (please complete the following information):**
 - OS: Windows 10
 - Version: v0.7.2
 - Any other relevant info: 

**Additional context**

**Comment by SpikeHD** [comment]
Vencord-based theming (which I should probably just remove from my fork since it's not how it works in Dorion lol) cannot and will not work due to the Discord CSP policy that I cannot change (see: https://github.com/SpikeHD/Dorion/issues/47#issuecomment-1641467116). Once/if Tauri changes to allow this, then they will work.

As for the hanging, send me the theme and I can take a look :+1:

**Comment by SpikeHD** [comment]
This should actually be fixed in d4a4209 and will be available in the next release
