### ISSUE TITLE
[Feature Request] possibility of moving from webkit to webkit-wpe for performance/footprint?

### ISSUE THREAD

**Issue by ldpr** [SpikeHD/Dorion#62]
**Is your feature request related to a problem? Please describe.**
webkit can be memory heavy, as dorion is built with footprint in mind WPE (https://webkit.org/wpe/, https://github.com/WebPlatformForEmbedded/WPEWebKit) might make sense?

**Comment by SpikeHD** [comment]
Great idea! Looks like it would take a considerable amount of effort since [Tauri has no plans to support it](https://github.com/tauri-apps/tauri/issues/4784), but like linked in that issue, it's possible that WPE could be turned into a [Tauri runtime](https://docs.rs/tauri-runtime/latest/tauri_runtime/trait.Runtime.html).

**Comment by SpikeHD** [comment]
As another note (mostly for myself), doesn't seem like WPE has Rust bindings, unless I'm blind, so I would also have to generate my own bindings probably.

**Comment by SpikeHD** [comment]
Since a move to WPE would be quite involved, and WebKitGTK seems to be getting better (I was doing Linux testing yesterday and memory usage was below that of Windows), I don't think I'll ever be supporting this
