### ISSUE TITLE
[Bug] broken bd theme

### ISSUE THREAD

**Issue by eltrevii** [SpikeHD/Dorion#64]
**Describe the bug**
this betterdiscord theme is broken

**To Reproduce**
install the theme

**Expected behavior**
the theme works

**Screenshots**
![image](https://github.com/SpikeHD/Dorion/assets/59333567/795aff38-f042-497e-aa78-d1dd175366fa)

**System Info (please complete the following information):**
 - OS: windows 10
 - Version: v0.8.0 (latest)
 - Any other relevant info: theme name is `SoftX`

**Additional context**
theme url: https://raw.githubusercontent.com/DiscordStyles/SoftX/deploy/SoftX.theme.css

**Comment by eltrevii** [comment]
nvm i (kinda) fixed it by adding `.theme` to the filenam (was only `SoftX.css`), now the font:
![image](https://github.com/SpikeHD/Dorion/assets/59333567/5e925fba-546c-4dc3-860b-243c86d49cbc)

**Comment by eltrevii** [comment]
the x button of notifications like the streamer mode one is also offset

**Comment by SpikeHD** [comment]
There's been a fair amount of discussion in the Discord about fonts and themes occasionally breaking slightly. It's a limitation that breaks specifically in Windows, and that I have some theories as to how to fix it, but nothing concrete.

For now, you can either manually change the font in the theme, or use a different theme. `nocturnal`, `slate` and `zelkBD` are some personal favs if you want reccos :P

**Comment by eltrevii** [comment]
🤨
![image](https://github.com/SpikeHD/Dorion/assets/59333567/3d0a8952-a672-4026-882c-473c449544a2)

**Comment by eltrevii** [comment]
i think imports might not be working properly

**Comment by eltrevii** [comment]
why would you have to whitelist fonts on a font parser?

**Comment by eltrevii** [comment]
btw the fonts you mentioned dont work

**Comment by SpikeHD** [comment]
Sorry, parser was the wrong word. Here is a bit of a high level explanation:

Because Discord CSP does not allow CSS, images, or fonts from unallowed sources, the CSS preprocessor does three things:
* CSS is processed to localize all CSS imports, then
* CSS is processed to localize all images into data URIs (eg `data:content/png;BASE64_DATA`), then
* CSS is processed to localize fonts
the *only* exception to the font rule is that fonts from `fonts.googleapis.com` are allowed, but my CSS preprocessor doesn't know that yet, so it downloads and outputs it as a data URI along with everything else.

The problem with this is that, on Windows specifically, there is a length limit to data URIs. If they are too large, they are not used at all. Not only does this cause most, if not all, font to not load, but this is also why large images often don't load properly.

That is why the CSS preprocessor needs the exception of `fonts.googleapis.com` in it, so it doesn't process those URIs. This will make the fonts work like normal.

**Comment by SpikeHD** [comment]
Answered in the previous comment:
> Because Discord CSP does not allow CSS, images, or fonts from unallowed sources, the CSS preprocessor does three things:

**Comment by SpikeHD** [comment]
That's what Discord decided, I guess. I believe that *technically* any data coming from a data URI is determined as coming from `self`, which is why it works

**Comment by eltrevii** [comment]
oh ok

**Comment by eltrevii** [comment]
also, can you please add a setting to disable multi-instance? its a bit annoying when i want to open dorion from the pinned taskbar icon

**Comment by SpikeHD** [comment]
Haha yea dw I’ve been meaning to make that just reveal the window for forever now, I promise I’ll get around to it soon 😄

**Comment by eltrevii** [comment]
k thanks

**Comment by SpikeHD** [comment]
Google fonts fixed in 31a9c2b48f5e992ec06f4c906d985f6e10cc78d9

**Comment by eltrevii** [comment]
release wen

**Comment by eltrevii** [comment]
???

**Comment by SpikeHD** [comment]
There is no release schedule. I make releases when I am ready to publish the new changes

**Comment by eltrevii** [comment]
why?

**Comment by SpikeHD** [comment]
Because there are things that still need to be done

**Comment by SpikeHD** [comment]
Also, to stop polluting this issue, I'd prefer you ask questions like this in [the Discord server](https://discord.gg/agQ9mRdHMZ)
