### ISSUE TITLE
[Bug] "Save and restart" not working properly

### ISSUE THREAD

**Issue by Temanor** [SpikeHD/Dorion#71]
**Describe the bug**
The "Save and restart" button in Dorion settings page seems to just close the application without restarting it

**To Reproduce**
Go into the Dorion settings page and click the "Save and restart" at the bottom of the page.

**Expected behaviour**
It should close the app, then reopen it.

**Screenshots**

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v0.9.0 (latest)

**Additional context**
This used to work on v0.8.0 if I don't remember incorrectly.

**Comment by Banaanae** [comment]
Also occurs when applying vencord plugins (same sys info as ^)

**Comment by Temanor** [comment]
Yeah, I'm not exactly sure what causes it.
Sometimes it happens, but when I did it now, enabling 2 other plugins, it worked just fine.

**Comment by SpikeHD** [comment]
Should hopefully be fixed in 617c0b909adedd2bf58604a417043502bf19968b

**Comment by Rigerhit047** [comment]
I do not know if it's related with my issue, but I am having this same problem on latest version, noticed when I was testing restarting for my issue.


For me, it restarts correctly every 1 from 10 tries, it's pretty rare for Dorion to actually restart correctly and not just closing, the process is gone too. I had the same problem since the short time I used Dorion v1.1.0
