### ISSUE TITLE
Windows 7 support?

### ISSUE THREAD

**Issue by c-sanchez** [SpikeHD/Dorion#9]
Hi, I'm using Windows 7 SP1 x64
For some reason Dorion does not work, the portable zip just starts and closes quickly (0.3.1), the installer gives an error (0.4.0).
![Dorion Windows 7 Installer](https://i.ibb.co/7JWjHkg/sshot-001.jpg)
I wonder if the program is supported, or if it can be fixed to run on Windows 7 as well.

**Comment by SpikeHD** [comment]
Should work on Win 7 but I don’t have a machine to test it. Will set up a VM in the future.

Currently portable installs for 4.0 don’t work fully because of the changes released in that version, which is why there are none, but its something I am aware of and working on.

Try installing webview manually (https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) and reopening the older portable version.

**Comment by SpikeHD** [comment]
The newest version, `0.4.1`, comes with a portable version that should theoretically work. I have not tested it, but it should have everything required. Just remember to install WebView2 first.

I will remember to include portable versions in all future releases.
