### ISSUE TITLE
[Feature Request] BetterDiscord plugin support

### ISSUE THREAD

**Issue by hhoneeyy** [SpikeHD/Dorion#91]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Support for openasar and betterdiscord plugins.

**Comment by SpikeHD** [comment]
Can't do OpenAsar, might be able to do BetterDiscord with this: https://github.com/tsukasa/BdBrowser

**Comment by hhoneeyy** [comment]
isnt that for web tho

**Comment by SpikeHD** [comment]
Yes, Dorion uses the web client, which is why OpenAsar isn’t really possible

**Comment by cozykitten** [comment]
Also Dorion already blocks tracking and supports Theming, aka everything that OpenAsar does.

I'd be really happy to see BD plugin support as well tho, I didn't switch to Dorion fully only cause I can't do without custom notification sounds (yes I'm a simple girl).

Or if it was possible to either choose which client mod to use (like ArmCord) or to be able to manually install one / a different one that would be amazing.
I'm also a little worried about using Vencord as opposed to the likes of BD,.. since Vencord offers a lot of ToS breaking plugins such as fake nitro or message logger, which is a thing that BD doesn't do, so I'm more worried about discord eventually doing something against Vencord than BD.

**Comment by SpikeHD** [comment]
> I didn't switch to Dorion fully only cause I can't do without custom notification sounds

Feel free to make a feature request 👍

**Comment by SpikeHD** [comment]
Oh also, while being able to choose which client mod to use definitely won’t happen (due to the fact all of my custom patches need to be rewritten per backend), you can already use *additional* ones on top of Vencord, if you’d like.

I also tend to lean towards the side of “every client mod is against ToS so you’re equally likely to have action taken against you”, so I don’t think using Vencord is anything to worry about. Any client mod can message log or fake nitro so long as you install a plugin for it, so if you’re afraid, don’t use those plugins!

**Comment by cozykitten** [comment]
> you can already use additional ones on top of Vencord using the Dorion plugin system, if you’d like.
huh? additional plugins or additional client mods?
I tried putting some BD plugins in Dorions plugin folder, they did show up there but didn't work.

**Comment by SpikeHD** [comment]
Haha additional client mods, BD plugins won’t work on their own. Check out how shelter works for example: #97

**Comment by cozykitten** [comment]
So if I understand correctly that means Shelter or any other client mod needs to have a version of their client mod that fits in one single js file? and then it could be added to Dorion?

It's basically just Notification Sounds and Remove Chat Buttons that I'm missing, No Track is already built into Vencord-Dorion.
(That's my personal issues tho)

Back to topic, I do think that it would be cool if the integrated vencord version could be made optional down the line so people have the choice to stick with that or drop in one other clientmod of their choice as Dorion plugin.
No clue if all the others even have a version for discord web, as far as I understood from reading this and the Shelter issue, only BD and Shelter have something like this?

**Comment by SpikeHD** [comment]
> So if I understand correctly that means Shelter or any other client mod needs to have a version of their client mod that fits in one single js file? and then it could be added to Dorion?

Yep! That's why BdBrowser doesn't just "work", it'd need a reworked implementation that doesn't depend on Chrome extension APIs and such.

> It's basically just Notification Sounds and Remove Chat Buttons

For notification sounds, [it's in the works](https://github.com/Vendicated/Vencord/pull/1827#issuecomment-1773864687) on the Vencord side. As for removing the chat buttons, you could probably add a snippet of CSS to whatever theme you're using that hides them. An inline CSS editor is [also something that's been asked for](https://github.com/SpikeHD/Dorion/issues/53) and that I've been considering fixing Vencords QuickCSS to do.

> It would be cool if the integrated vencord version could be made optional down the line so people have the choice to stick with that or drop in one other clientmod of their choice as Dorion plugin.

Totally agree, but because Dorion depends on Vencords client patching helpers and utils right now (it makes writing Dorion-specific features sooooo easy), all of the frontend stuff (Dorion settings page, flux dispatcher related things, etc.) would need to be either rewritten entirely, or rewritten per-client-mod. For example, a "Dorion" Shelter plugin could be made the replicates everything the current Vencord fork does, but that requires a fair amount of work.

> No clue if all the others even have a version for discord web, as far as I understood from reading this and the Shelter issue, only BD and Shelter have something like this?

I don't know of, like, an exhaustive list of client mods or anything, but any client mod that is supported in-browser via userscript (eg. Vencord, that's why I chose it) should automatically be supported by Dorion. Any that use something like a Chrome extension (eg. BdBrowser) would need a rework, and anything that is desktop-only (eg. OpenAsar) is entirely unsupported and likely never will be.

**Comment by Temanor** [comment]
> An inline CSS editor is [also something that's been asked for](https://github.com/SpikeHD/Dorion/issues/53)

So you didn't actually forget 😄

**Comment by SpikeHD** [comment]
Gonna close this since I don't plan on supporting/doing it myself.
